# Permalinks
permalink:           pretty

# Setup
title:               Bio-I/O
tagline:             A metabolomics and genomics company.
url:                 http://bioio.tech
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Tim Peterson, CEO
  url:               https://twitter.com/bioio
  email:             timrpeterson@wustl.edu

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/tim-peterson/bioio

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
